### ISSUE TITLE
Palabra período sin acentos

### ISSUE THREAD

**Issue by CamiCorrales** [uvsy-angular-web/angular-universy-web-client#66]
Buscar todos los lugares donde diga "periodo" y ponerle acento <3 

![imagen](https://user-images.githubusercontent.com/38230659/99156070-eb567e80-269c-11eb-9883-32fa4b11d8d5.png)

![imagen](https://user-images.githubusercontent.com/38230659/99156075-f3162300-269c-11eb-99d1-6e118942e01d.png)

**Comment by maxipom** [comment]
Vimos que esta bien que no lleve acentos
