### ISSUE TITLE
Error al borrar Materia

### ISSUE THREAD

**Issue by CamiCorrales** [uvsy-angular-web/angular-universy-web-client#72]
carrera: Carrera de Cami
plan: Nombre del Plan Carrera Cami
materia: Materia A a a a a a a a a a a a a a a a a a a a a
Click eliminar: 

![imagen](https://user-images.githubusercontent.com/38230659/99160218-95e19800-26c3-11eb-8ca3-75905d528e19.png)

message: "java.sql.SQLException: Unable to run delete stmt on object Subject(id=aa15a4c4-f1dd-4506-9c51-ad75e3ef1511, name=Materia A a a a a a a a a a a a a a a a a a a a a, codename=WEB, level=1, programId=f2bd9b6c-009c-4dc5-a97f-f2ec62f426f3, program=Program(id=f2bd9b6c-009c-4dc5-a97f-f2ec62f426f3, name=null, careerId=null, career=null, yearFrom=null, yearTo=null, southHemisphere=null, hours=null, points=null, amountOfSubjects=null, active=null, createdAt=null, updatedAt=null), hours=2, points=1, active=false, optative=true, correlatives=com.j256.ormlite.dao.EagerForeignCollection@1, createdAt=2020-11-15 00:00:33.542012, updatedAt=2020-11-15 00:00:33.542012): DELETE FROM "subject" WHERE "id" = ?"

![imagen](https://user-images.githubusercontent.com/38230659/99160200-4e5b0c00-26c3-11eb-8e70-a5f930269413.png)

Dato que quizas tiene que ver: La materia ya está "en uso" por un usuario mobile, es decir, ya tiene estado aprobado y esta valorada  - (está el error que aunque el plan no esta publicado, lo puedo seleccionar igual desde mobile).

**Comment by maxipom** [comment]
Hay que validar las materias electivas :thinking:
