### ISSUE TITLE
Se rompe estilo si registro una comision de nombre muy largo y agrego luego una materia

### ISSUE THREAD

**Issue by CamiCorrales** [uvsy-angular-web/angular-universy-web-client#73]
1) Registrar una comisión con 45 caracteres en mayuscula.
2) Registrar una materia:

![imagen](https://user-images.githubusercontent.com/38230659/99160290-6d0dd280-26c4-11eb-858d-2d51967d070e.png)

**Comment by maxipom** [comment]
Definitivamente tenemos que agregarle un maximo de caracteres a la comision XD

**Comment by maxipom** [comment]
Se resolveria con el issue #71
