### ISSUE TITLE
Se repite "imprimir" y "publicar" al intentar publicar plan

### ISSUE THREAD

**Issue by CamiCorrales** [uvsy-angular-web/angular-universy-web-client#74]
![imagen](https://user-images.githubusercontent.com/38230659/99160316-d5f54a80-26c4-11eb-8979-41323d4420a3.png)

**Comment by maxipom** [comment]
@CamiCorrales  Esto fue echo a proposito en su momento, 
la idea es que cuando lo estas viendo en "Detalle" onda el plan ya esta publicado, lo puedas imprimir directamente desde arriba
pero cuando entras a esta pantalla antes de publicar el plan, esta bueno que el boton este al fondo asi pasas por toda la pantall

Te parece que le ponga un comportamiento dinamico? :thinking: 
Que aveces este arriba y aveces abajo dependiendo por donde entres :thinking:

**Comment by CamiCorrales** [comment]
Ah es buena esa, que si estas scroll up te aparezcan los de arriba, y sino los de abajo ! 
Si no es muy dificil si estaria bueno hacerlo asi , sería una mejora :)

**Comment by maxipom** [comment]
Mmm no del scroll, sino si el plan esta publicado que aparezca arriba
y si el plan noe sta publicado te aparezca abajo
